name: SonarQube Code Scan Only

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------
      # 1. CHECKOUT
      # --------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # required for SonarQube

      # --------------------------------------
      # 2. SONARQUBE SCAN (TEST)
      # --------------------------------------
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=NextJSProject
            -Dsonar.projectName=NextJSProject
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**
